---
title: 'DETECTING DISEASE: BAYES LAB'
author: "Patrick Poleshuk"
date: "9/24/2020"
output:
  pdf_document: default
  html_document:
    df_print: paged
---
## Using Bayes for Pregnancy Data
```{r setup1, include=TRUE, echo=TRUE}
true_neg_test_pos <- 0
total_pos <- 0
for (i in 1:10000) {
  Infected <- rbinom(1, 1, 0.75)
  if (Infected == 1) {
    if (rbinom(1, 1, .95) == 1) {
      total_pos <- total_pos + 1 }
  } else {
    if (rbinom(1, 1, .02) == 1) {
      total_pos <- total_pos + 1
      true_neg_test_pos <- true_neg_test_pos + 1 }
  } 
}
print(true_neg_test_pos)
print(total_pos)
print(true_neg_test_pos / total_pos) 
```
## Using the empirical data.

```{r setup2, include=TRUE}
true_neg_test_pos <- 0
total_pos <- 0
for (i in 1:10000) {
  Infected <- rbinom(1, 1, 0.8)
  if (Infected == 1) {
    if (rbinom(1, 1, 1) == 1) {
      total_pos <- total_pos + 1 }
  } else {
    if (rbinom(1, 1, 1/4) == 1) {
      total_pos <- total_pos + 1
      true_neg_test_pos <- true_neg_test_pos + 1 }
  } 
}
print(true_neg_test_pos)
print(total_pos)
print(true_neg_test_pos / total_pos) 
```
